macOS: raise deployment target to 10.13
```
error: 'visit<(lambda at ...include/openPMD/backend/Attribute.hpp:239:9),
              std::variant<...> &>'
is unavailable: introduced in macOS 10.13
```

`std::filesystem` needs macOS 10.15:
```
share/openPMD/thirdParty/toml11/toml/parser.hpp:2166:65:
error: 'path' is unavailable: introduced in macOS 10.15
basic_value<Comment, Table, Array> parse(const std::filesystem::path& fpath)
                                                                ^
/Applications/Xcode_13.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include/c++/v1/filesystem:902:24:
note: 'path' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS path {
                       ^
```